name: rickandmorty_app
description: "Rick and Morty App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  formz: ^0.8.0
  get_it: ^8.0.3
  http: ^1.2.2
  photo_view: ^0.15.0
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue/ComicNeue-Regular.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/ComicNeue/ComicNeue-Italic.ttf
          style: italic
        - asset: assets/fonts/ComicNeue/ComicNeue-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ComicNeue/ComicNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/ComicNeue/ComicNeue-LightItalic.ttf
          weight: 300
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Italic.ttf
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono/RobotoMono-SemiBoldItalic.ttf
          weight: 600
          style: italic